apiVersion: v1
kind: Service

metadata:
  name: {{.Values.name}}

spec:
  type: LoadBalancer
  ports:
    - port: {{.Values.port}}
      targetPort: {{.Values.port}}
  selector:
    microservice: {{.Values.name}}
